# Generated by Django 4.2.3 on 2023-07-18 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_image2_product_image3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image3',
        ),
    ]
